config/routes.rb
Rails.application.routes.draw do
  put '/vote/' => 'votes#create'
  put '/unvote/' => 'votes#destroy'

  get 'collection', action: :collection, controller: 'categories'

  get 'sign_in', action: :sign_in, controller: 'users'
  post 'login', action: :login, controller: 'users'
  delete 'log_out', action: :destroy, controller: 'users'

  resources :users
  resources :articles
  resources :categories

  root 'articles#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :category
  has_one_attached :image
  has_many :votes

  validates :title, presence: true
  validates :text, presence: true
  validates :category_id, presence: true
  validates :image, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, presence: true
  validates :priority, presence: true, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, foreign_key: :author_id, class_name: 'Article'
  has_many :votes

  validates :name, presence: { message: 'This name already exists' }
  validates :name, uniqueness: { message: 'Name must be unique' }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article, counter_cache: true

  validates :user_id, presence: true
  validates :article_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :user

  private

  def user
    @user = if session[:current_user_id].is_a? Integer
              User.find(session[:current_user_id])
            else
              User.first
            end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.all

    @categories = Category.all.sort_by(&:priority).reverse.first(4)

    @user = if session[:current_user_id].is_a? Integer
              User.find(session[:current_user_id])
            else
              User.first
            end

    @main_article = @articles.order('votes_count DESC')
  end

  # GET /articles/1
  # GET /articles/1.json
  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    current_user = User.find(session[:current_user_id])
    @article = current_user.articles.build(article_params)
    @article.image.attach(params[:article][:image])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image, :category_id)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to new_article_path, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def show; end

  def collection
    @article = Article.find(params[:id])

    @collection = Article.where(category_id: @article.category_id).includes(:author)

    @user = if session[:current_user_id].is_a? Integer
              User.find(session[:current_user_id])
            else
              User.first
            end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Category was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:current_user_id] = @user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]

  def index
    @users = User.all
  end

  def show
    @collections = @user.votes
  end

  def new
    @user = User.new
  end

  def edit; end

  def sign_in
    @user = User.new
  end

  def login
    if User.find_by(name: params[:name])
      @user = User.find_by(name: params[:name])
      session[:current_user_id] = @user.id
      flash[:notice] = "Welcome back #{@user.name}!"
      redirect_to root_path
    else
      flash[:notice] = 'Register a new account here.'
      redirect_to new_user_path
    end
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:current_user_id] = @user.id
        format.html { redirect_to root_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    session.delete(:current_user_id)
    redirect_to root_path
  end

  private

  def set_user
    @user = if session[:current_user_id].is_a? Integer
              User.find(session[:current_user_id])
            else
              User.find(params[:id])
            end
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @vote = @article.votes.build(vote_params)

    if @vote.save
      flash[:notice] = 'You liked this article!'
      redirect_to "/collection?id=#{@vote.article.id}"
    else
      flash[:notice] = @vote.errors.full_messages
      redirect_to root_path
    end
  end

  def destroy
    @vote = Vote.find_by(user_id: params[:user_id], article_id: params[:article_id])
    @prev_vote = params[:article_id]

    if @vote.destroy
      flash[:notice] = 'You disliked this article!'
      redirect_to "/collection?id=#{@prev_vote}"
    else
      flash[:notice] = @vote.errors.full_messages
      redirect_to root_path
    end
  end

  private

  def vote_params
    params.permit(:user_id, :article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-container">
    <div class="form-style-2">
    <div class="form-style-2-heading"> Take your time to write an incredible article, <%= @user.name %>.</div>
      <div class="field">
        <%= form.text_field :title, placeholder: 'Write a title for your article', class:'input-field' %>
      </div>

      <div class="field">
        <%= form.text_area :text, placeholder: 'Start writing your article here...', class: 'textarea-field'%>
      </div>

      <div class="field">
        <%= form.label 'Add a picture for your article.' %>
        <%= form.file_field :image %>
      </div>

      <div class="field">
        <%= form.label 'Select a category for the article.' %>
        <%= form.select(:category_id, options_from_collection_for_select(Category.all, :id, :name, :priority), prompt: true, :selected => 1, class: 'select-field') %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

  <section class="articles-frontpage">
    <div class="frontpage">
      <% if @main_article.present? %>
      <%= link_to ' ', @main_article.first, class: 'click-image'%>
      <%= image_tag(@main_article.first.image, class:"article-image") %>
      <h3 class="text"><%= @main_article.first.title%></h3>
      <p class="text"><%= @main_article.first.text%></p>
      <% end %>
    </div>
    <div class="articles-column">
      <div>
        <% if @main_article.second.present? %>
        <%= link_to ' ', @main_article.second, class: 'click-image'%>
        <%= image_tag(@main_article.second.image, class:"article-image") %>
        <h3><%= @main_article.second.title%></h3>
        <% end %>
      </div>

      <div>
        <% if @main_article.third.present? %>
        <%= link_to ' ', @main_article.third, class: 'click-image'%>
        <%= image_tag(@main_article.third.image, class:"article-image") %>
        <h3><%= @main_article.third.title%></h3>
        <% end %>
      </div>
    </div>
  </section>
  <section class="articles-row">
    <% @categories.each do |category| %>
      <div>
        <% if category.articles.sort_by(&:created_at).last.present? %>
          <%= link_to ' ', collection_path(id: category.articles.sort_by(&:created_at).last), class: 'click-image'%>
          <%= image_tag(category.articles.sort_by(&:created_at).last.image, class:"article-image") %>
          <h3><%= category.articles.sort_by(&:created_at).last.category.name%></h3>
          <p><%= category.articles.sort_by(&:created_at).last.title%></p>
        <% end %>
      </div>
    <% end %>
  </section>

app/views/articles/new.html.erb
<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<article class="article-container">

  <%= image_tag(@article.image) if @article.image.attached? %>

  <p>
    <strong>Author:</strong>
    <%= @article.author.name %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @article.title %>
  </p>

  <p>
    <strong>Text:</strong>
    <%= simple_format(@article.text) %>
  </p>

  <p>
    <strong>Category:</strong>
    <%= @article.category.name %>
  </p>

  <% if session[:current_user_id] == @article.author.id %>
  <p><%= link_to 'Edit Article', edit_article_path(@article) %></p>
  <% end %>
</article>

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-container">
    <div class="form-style-2">
    <div class="form-style-2-heading">Categories are sorted in frontpage based on priority.</div>
      <div class="field">
        <%= form.text_field :name, placeholder: 'Write a name for the cateogry', class:'input-field' %>
      </div>

      <div class="field">
        <%= form.number_field :priority, placeholder: 'Number of priority' %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  </div>
<% end %>

app/views/categories/collection.html.erb
<section class="articles-category">
  <div>
    <% @collection.each do |collection| %>
      <div>
        <%= image_tag(collection.image, class:"article-image") %>
        <div class="category-article-content">
          <h3><%= simple_format(collection.category.name) %></h3>
          <h2><%= collection.title %></h2>
          <h2>Author:
            <%= collection.author.name %></h2>
          <p class="text"><%= collection.text %></p>
          <% if session[:current_user_id].is_a? Integer %>
            <% if collection.votes.find_by(user_id: @user).present? %>
              <h3><%= link_to 'unvote', unvote_path(user_id: @user, article_id: collection), method: :put %></h3>
            <% else %>
              <h3><%= link_to 'vote', vote_path(user_id: @user, article_id: collection), method: :put %></h3>
            <% end %>
            <% if session[:current_user_id] == collection.author.id %>
            <h3><%= link_to 'Edit Article', edit_article_path(collection) %></h3>
            <% end %>
          <% end %>

           <h3><%= link_to 'Read more', collection %></h3>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @category.priority %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Station</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script src="https://kit.fontawesome.com/8e996abce9.js"></script>
  </head>

  <body class="main">
    <div class="main-container">
      <header class="navbar">
        <div>
          <h1><%= link_to 'The Station', root_path %></h1>
        </div>
        <div>
          <ul>
            <li><a href="/" class="navbar-selected">Home</a></li>
            <% if session[:current_user_id].is_a? Integer %>
            <li><%= link_to 'Write an Article', new_article_path %></li>
            <li><%= link_to 'Add Category', new_category_path %></li>
            <% end %>
          </ul>
        </div>
        <div class="navbar-login">
          <div>
            <% if session[:current_user_id].is_a? Integer %>
              <h3>Current Profile: <%= link_to "#{@user.name}", @user %> | <%= link_to 'Log out', log_out_path, method: :delete %></h3>
            <% else %>
              <%= link_to 'LOGIN', sign_in_path %> | <%= link_to 'REGISTER', new_user_path %>
            <% end %>
          </div>
          <div>
            <i class="fas fa-search"></i>
          </div>
        </div>
      </header>
      <%= yield %>
      </div>
      <div class="main-container">
        <footer>
          <div class="footer-logo">
            <h1><a href="#">The Station</a></h1>
          </div>
          <div class="footer-terms">
            <ul>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Terms & Conditions</a></li>
              <li class="copyrights-text">Copyrights 2020. All rights reserved.</li>
            </ul>
          </div>
          <div class="footer-social">
            <p>Connect with us:</p>
            <div>
              <a href="#"><i class="fab fa-twitter-square"></i></a>
              <a href="#"><i class="fab fa-instagram-square"></i></a>
              <a href="#"><i class="fab fa-facebook-square"></i></a>
            </div>
          </div>
        </footer>
      </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">o
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-container">
    <div class="form-style-2">
    <div class="form-style-2-heading"> Creating an account </div>
    <div class="field">
      <%= form.label 'Write a name for this account.' %>
      <%= form.text_field :name, class: 'input-field' %>
    </div>

    <div class="actions">
      <%= form.submit 'Create Account'%>
    </div>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="form-container">
  <% if session[:current_user_id].is_a? Integer %>
    <% if session[:current_user_id] = @user.id %>
      <h3> All your liked articles </h3>
    <% else %>
      <h3> Liked articles by <%= @user.name %> </h3>
    <% end %>
  <% else %>
      <h3> Liked articles by <%= @user.name %> </h3>
  <% end %>
  <div class="articles-category">
    <div>
      <% @collections.each do |collection| %>
        <div>
          <%= image_tag(collection.article.image, class:"article-image") %>
          <div class="category-article-content">
            <h3><%= simple_format(collection.article.category.name) %></h3>
            <h2><%= collection.article.title %></h2>
            <h2>Author:
              <%= collection.article.author.name %></h2>
            <p class="text"><%= collection.article.text %></p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/sign_in.html.erb
<%= form_with url: login_path  do |f| %>
<div class="form-container">
  <div class="form-style-2">
    <div class="form-style-2-heading"> Creating an account </div>
        <%= f.label 'Name of the account' %>
        <%= f.text_field :name, class: 'input-field'%>
        <%= f.submit 'Login' %>
  </div>
</div>

<% end %>